# config/packages/workflow.yaml
framework:
    workflows:
        backpack_publishing:
            type: 'workflow' # or 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\Backpack
            initial_marking: draft
            places:
                - draft
                - abandonned
                - published
                - archived
            transitions:
                toPublish:
                    from: draft
                    to:   published
                toDraft:
                    from: [published, abandonned,archived]
                    to:   draft
                toAbandonne:
                    from: [draft, published, archived]
                    to:   abandonned
                toArchive:
                    from: [draft, published]
                    to:   archived