App\Entity\Comment:
  properties:
    subject:
      - NotBlank: ~
      - Length:
          min: 2
          max: 255
          minMessage: 'Le sujet "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le sujet "{{ value }}" ne peut pas avoir plus de 255 caractères'