App\Entity\UnderRubric:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [underThematic, name]
        errorPath: name
        message: 'Le nom de la sous rubrique "{{ value }}" est déjà déclaré pour cette thématique.'
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 2
          max: 255
          minMessage: 'Le nom "{{ value }}" doit avoir plus de 2 caractères'
          maxMessage: 'Le nom "{{ value }}" ne peut pas avoir plus de 255 caractères'